// Generated by CoffeeScript 1.6.3
(function() {
  var iDevices, iOS, v, _i, _len;

  iDevices = [/iPad/, /iPhone/, /iPod/];

  iOS = false;

  for (_i = 0, _len = iDevices.length; _i < _len; _i++) {
    v = iDevices[_i];
    if (navigator.userAgent.match(v)) {
      iOS = true;
    }
  }

  $(document).ready(function() {
    if (!iOS) {
      return $('body').append("<p class='warning'>You are not running on iDevices<p>");
    }
  });

}).call(this);
