// Generated by CoffeeScript 1.6.3
(function() {
  var getLocation;

  getLocation = function(json) {
    var href, htmlString, location, nodes, re, re2;
    htmlString = htmlDecode(json['HtmlBody']);
    nodes = $.parseHTML(htmlString);
    href = $('a', nodes).attr('href');
    re = /%20/g;
    re2 = /%20C/g;
    return location = href.replace(re, ' ').replace(re2, ',');
  };

}).call(this);
