// Generated by CoffeeScript 1.6.3
(function() {
  var getLocation, host, htmlDecode;

  host = "localhost:4567";

  getLocation = function(json) {
    var href, htmlString, location, nodes, re, re2;
    htmlString = htmlDecode(json['HtmlBody']);
    nodes = $.parseHTML(htmlString);
    href = $('a', nodes).attr('href');
    re = /%20/g;
    re2 = /%2C/g;
    return location = href.replace(re, ' ').replace(re2, ',');
  };

  htmlDecode = function(string) {
    return $('<div />').html(string).text();
  };

  $('#getJSON').click(function() {
    return $.get("http://" + host + "/json", function(data) {
      var $link, googleLocation, location;
      location = getLocation(data);
      googleLocation = parseURL(location);
      $link = $('<a />').attr('href', googleLocation).text("From: " + data['From'] + " On " + data['Date']);
      return $('#link').append($link);
    });
  });

}).call(this);
